### ISSUE TITLE
Feature Request: Convert from Python to zsh

### ISSUE THREAD

**Issue by kylejericson** [nstrauss/jamf-extension-attributes#1]
Hey since Python is going to be killed with the next macOS update can you convert this to zsh so we can keep using this?

**Comment by nstrauss** [comment]
I'm no longer using Jamf Pro and have no way to test these if I wanted to. The Python EAs are sufficiently complex enough I would not want to convert to zsh. They would most likely be made Python 3 compatible. It would be up to the admin to supply their own interpreter. If that works for you, what EAs specifically would you want to be Python 3 compatible? I would also gladly accept a PR.

**Comment by uqperryk** [comment]
It would be fantastic if the nomadlogin_mechs.py one could be updated to work with python3.  I've briefly tried using MacAdmins Managed Python3 install and receive the following error:

```
╰─ ./noload_authmechs.py                                                                                                                        ─╯
Traceback (most recent call last):
  File "/Users/uqpkollm/Desktop/./noload_authmechs.py", line 50, in <module>
    main()
  File "/Users/uqpkollm/Desktop/./noload_authmechs.py", line 26, in main
    authdb = get_login_authdb()
  File "/Users/uqpkollm/Desktop/./noload_authmechs.py", line 19, in get_login_authdb
    return plistlib.readPlistFromString(stdout)
AttributeError: module 'plistlib' has no attribute 'readPlistFromString'
```

Although I can appreciate that you yourself might not be available to do this considering you are no longer using Jamf Pro, perhaps someone else will see this however.

We use this EA to detect when major OS upgrades clear the NoLoAD settings and we need to run authchanger again.

**Comment by nstrauss** [comment]
@kylejericson @uqperryk PR https://github.com/nstrauss/jamf-extension-attributes/pull/2 updates these EAs to be Python 3 compatible. Be sure to read the README note. You'll want to make sure you're using a known Python 3 interpreter path.

https://github.com/nstrauss/jamf-extension-attributes/blob/3fa2b514adce38aec132e54f269c1548c48d8ebd/README.md?plain=1#L4-L6

**Comment by perryk** [comment]
Thank you, it is working well.
